### ISSUE TITLE
Does not run on Wayland

### ISSUE THREAD

**Issue by neomoth** [fdibaldassarre/linux-shimeji#7]
This software does not run underneath Wayland. It starts but it cannot display Shimeji, spitting out this error ad infinitum:
```
java.lang.IllegalAccessException: class com.sun.jna.platform.WindowUtils$X11WindowUtils cannot access class sun.awt.X11GraphicsConfig (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @ee9a8d6
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.base/java.lang.reflect.Method.invoke(Method.java:560)
	at com.sun.jna.platform.WindowUtils$X11WindowUtils.getVisualID(WindowUtils.java:1629)
	at com.sun.jna.platform.WindowUtils$X11WindowUtils.getAlphaCompatibleGraphicsConfiguration(WindowUtils.java:1650)
	at com.sun.jna.platform.WindowUtils.getAlphaCompatibleGraphicsConfiguration(WindowUtils.java:1974)
	at com.group_finity.mascot.x11.X11TranslucentWindow.<init>(X11TranslucentWindow.java:49)
	at com.group_finity.mascot.x11.NativeFactoryImpl.newTransparentWindow(NativeFactoryImpl.java:31)
	at com.group_finity.mascot.Mascot.<init>(Mascot.java:53)
	at com.group_finity.mascot.Main.createMascot(Main.java:187)
	at com.group_finity.mascot.Main.run(Main.java:71)
	at com.group_finity.mascot.Main.main(Main.java:57)
```
Would you consider adding Wayland support, or is that not a thing that'd be possible with this software?

**Comment by fdibaldassarre** [comment]
Hi,
the program should work under wayland actually.

Are you using java 11?
```
$ java -version
openjdk version "11.0.22" 2024-01-16
OpenJDK Runtime Environment (build 11.0.22+7-post-Debian-2)
OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Debian-2, mixed mode, sharing)
```

If not you can download it from the official website: https://jdk.java.net/java-se-ri/11-MR2

**Comment by neomoth** [comment]
Switched to java 11 and now I get this output, still no shimeji on screen.
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.jna.platform.WindowUtils$X11WindowUtils (file:/home/neomoth/src/shimeji/target/linux-shimeji-0.0.1-SNAPSHOT-jar-with-dependencies.jar) to method sun.awt.X11GraphicsConfig.getVisual()
WARNING: Please consider reporting this to the maintainers of com.sun.jna.platform.WindowUtils$X11WindowUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Warning: Nashorn engine is planned to be removed from a future JDK release
Exception in thread "Thread-2" java.lang.UnsatisfiedLinkError: libjawt.so: cannot open shared object file: No such file or directory
	at com.sun.jna.Native.getWindowHandle0(Native Method)
	at com.sun.jna.Native$AWT.getComponentID(Native.java:2383)
	at com.sun.jna.Native$AWT.getWindowID(Native.java:2359)
	at com.sun.jna.Native.getWindowID(Native.java:316)
	at com.group_finity.mascot.x11.X11TranslucentWindow.updateX11(X11TranslucentWindow.java:87)
	at com.group_finity.mascot.x11.X11TranslucentWindow.updateImage(X11TranslucentWindow.java:189)
	at com.group_finity.mascot.Mascot.apply(Mascot.java:153)
	at com.group_finity.mascot.Manager.tick(Manager.java:177)
	at com.group_finity.mascot.Manager$2.run(Manager.java:118)
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: libjawt.so: cannot open shared object file: No such file or directory
	at com.sun.jna.Native.getWindowHandle0(Native Method)
	at com.sun.jna.Native$AWT.getComponentID(Native.java:2383)
	at com.sun.jna.Native.getComponentID(Native.java:326)
	at com.sun.jna.platform.WindowUtils$X11WindowUtils.getDrawable(WindowUtils.java:1747)
	at com.sun.jna.platform.WindowUtils$X11WindowUtils.access$900(WindowUtils.java:1564)
	at com.sun.jna.platform.WindowUtils$X11WindowUtils$X11TransparentContentPane.paintDirect(WindowUtils.java:1812)
	at com.sun.jna.platform.WindowUtils$NativeWindowUtils$TransparentContentPane.paint(WindowUtils.java:375)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:78)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:115)
	at java.desktop/java.awt.Container.paint(Container.java:2002)
	at java.desktop/java.awt.Window.paint(Window.java:3940)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:876)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by fdibaldassarre** [comment]
So now it cannot find `libjawt.so`.

That file should be in the folder `/usr/lib/jvm/java-11-openjdk-amd64/lib/`

Can you try to run the application using this script?
```
#!/bin/bash

export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export PATH="$JAVA_HOME/bin:$PATH"

export LD_LIBRARY_PATH="/usr/lib/jvm/java-11-openjdk-amd64/lib/"
java -classpath target/linux-shimeji-0.0.1-SNAPSHOT-jar-with-dependencies.jar -Xmx1000m com.group_finity.mascot.Main
```

If it still cannot find `libjawt.so` you will need to set LD_LIBRARY_PATH to the folder containing it.
